### ISSUE TITLE
Datum Arrays with single items do not stay as arrays

### ISSUE THREAD

**Issue by rdbartram** [gaelcolas/Datum#39]
Hey Gael,

with Resolve-DatumPath line 34:

`$PathItem = ($CurrentNode.$($ExecutionContext.InvokeCommand.ExpandString($StackItem)))`

This is breaking my merges as I want to add a single hashtable to an array of hashtables.

Maybe I'm doing something wrong but when I run Get-FileProviderData in PowerShell, it maintains the object as an array. However, when I run the Resolve-DatumPath or Resolve-NodeProperty then it loses its original type.

I've isolated the problem to when this command it run but with strictmode on/off json/yaml/psd1. It doesn't make a difference.

Do you know what this could be or how to solve it?

Thanks

**Comment by rdbartram** [comment]
I tested initially with 0.0.28 and then with the current version in master branch. I don't think it's so much a Datum problem as a PowerShell problem.  I thought maybe you knew about it and we could implement something to mitigate it

**Comment by gaelcolas** [comment]
When you say:
> "I want to add a single hashtable to an array of hashtables"
That's something I do often and it works for me. I'll try to document it and demo to make sure we're trying the same thing.
I also need to document the merge behaviour because you probably want to make sure the Key in use is set to `merge_hash_arrays: deep` or similar.

If you have the config data code somewhere or an example, I can have a look.

**Comment by gaelcolas** [comment]
I don't know if you found those example buried away, but that might help:
https://github.com/gaelcolas/Datum/blob/master/Datum/tests/Integration/assets/DSC_ConfigData/Datum.yml#L74-L82


Which merges arrays of hashtable based on key/value tuples.
From:
https://github.com/gaelcolas/Datum/blob/master/Datum/tests/Integration/assets/DSC_ConfigData/Environments/DEV.yml#L60-L71

https://github.com/gaelcolas/Datum/blob/master/Datum/tests/Integration/assets/DSC_ConfigData/Roles/MergingTest.yml#L49-L68

**Comment by rdbartram** [comment]
I did find some examples and the tuples so work well for merging multiple array. I'll take a look and see what I can find out. Problem is that there is a if that query if both types are arrays or not. I'll keep you posted

**Comment by gaelcolas** [comment]
Yep, it had to same type (I.e. array of 1). I had it differently before,
but it would create problems and inconsistencies in multilayer merges of
some types, do I took a more strict approach.

Iirc, one issue is when you have a single hashtable to merge with an array
of hashtable... The first type had different type of merges (hash, deep) to
the second (tuple).

Another point is that it'd make reading the policy (data) much harder, as
you wouldn't know what it should end up looking.

**Comment by rdbartram** [comment]
Resolved with PR #42

**Comment by raandree** [comment]
This is not resolved. I have some issues with single item arrays of BaseType. It may work already with hash arrays tough.

**Comment by gaelcolas** [comment]
@raandree is that fixed now? (I believe it is with the recent PRs)

**Comment by gaelcolas** [comment]
I think this has been fixed
